In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/home/barbora/PycharmProjects/DP-SecuritySDN/a.txt", delimiter=" ")
data.head(10)

           State             Time     Src_IP
0  NEW_PACKET_IN  02:58:15.039245  10.0.0.80
1  NEW_PACKET_IN  02:58:15.039853   10.0.0.1
2  NEW_PACKET_IN  02:58:15.040320   10.0.0.2
3  NEW_PACKET_IN  02:58:15.040785   10.0.0.3
4  NEW_PACKET_IN  02:58:15.089781   10.0.0.4
5  NEW_PACKET_IN  02:58:15.090313   10.0.0.5
6  NEW_PACKET_IN  02:58:15.090739   10.0.0.6
7  NEW_PACKET_IN  02:58:15.091195   10.0.0.4
8  NEW_PACKET_IN  02:58:15.091621   10.0.0.5
9  NEW_PACKET_IN  02:58:15.092076   10.0.0.7

In [3]:
county = data.groupby(['State']).count()
county

                      Time  Src_IP
State
NEW_PACKET_IN         1130    1130
PASSED                 490     490
REJECTED               640     640
REJECTED_blacklisted   135     135

In [4]:
grouped_data = data.groupby(['State', 'Src_IP']).count()
grouped_data

                                Time
State                Src_IP
NEW_PACKET_IN        10.0.0.1     14
                     10.0.0.10    13
                     10.0.0.11    13
                     10.0.0.12    13
                     10.0.0.13    13
                     10.0.0.14    13
                     10.0.0.15    13
                     10.0.0.16    13
                     10.0.0.17    13
                     10.0.0.18    13
                     10.0.0.19    13
                     10.0.0.2     14
                     10.0.0.20    13
                     10.0.0.21    13
                     10.0.0.22    13
                     10.0.0.23    13
                     10.0.0.24    13
                     10.0.0.25    13
                     10.0.0.26    14
                     10.0.0.27    14
                     10.0.0.28    14
                     10.0.0.29    14
                     10.0.0.3     14
                     10.0.0.30    14
                     10.0.0.31    14
                     10.0.0.32    14
                     10.0.0.33    14
                     10.0.0.34    13
                     10.0.0.35    13
                     10.0.0.36    13
...                              ...
REJECTED_blacklisted 10.0.0.6      1
                     10.0.0.60     1
                     10.0.0.61     1
                     10.0.0.62     1
                     10.0.0.63     1
                     10.0.0.64     1
                     10.0.0.65     1
                     10.0.0.66     1
                     10.0.0.67     1
                     10.0.0.68     1
                     10.0.0.69     1
                     10.0.0.7      1
                     10.0.0.70     1
                     10.0.0.71     1
                     10.0.0.72     1
                     10.0.0.73     1
                     10.0.0.74     1
                     10.0.0.75     1
                     10.0.0.8      1
                     10.0.0.80     5
                     10.0.0.81     4
                     10.0.0.82     4
                     10.0.0.83     4
                     10.0.0.84     4
                     10.0.0.85     4
                     10.0.0.86     4
                     10.0.0.87     4
                     10.0.0.88     4
                     10.0.0.89     3
                     10.0.0.9      1

[340 rows x 1 columns]

In [5]:
data['Time'] = data['Time'].apply(lambda x: x.split('.')[0])
data.groupby(['Time']).count().head(100)

          State  Src_IP
Time
02:58:15    280     280
02:58:16    285     285
02:58:17    200     200
02:58:18    184     184
02:58:19    200     200
02:58:20    184     184
02:58:21    150     150
02:58:22    121     121
02:58:23    150     150
02:58:24    117     117
02:58:25    150     150
02:58:26    117     117
02:58:27     24      24
02:58:29     48      48
02:58:31     48      48
02:58:40    137     137

In [6]:
data['Cat'] = 'Good boys'
data.loc[data['Src_IP'].isin(['10.0.0.80', '10.0.0.81', '10.0.0.82', '10.0.0.83', '10.0.0.84', '10.0.0.85', '10.0.0.86', '10.0.0.87', '10.0.0.88', '10.0.0.89', '10.0.0.90', '10.0.0.91', '10.0.0.92', '10.0.0.93', '10.0.0.94', '10.0.0.95', '10.0.0.96', '10.0.0.97', '10.0.0.98', '10.0.0.99']), 'Cat'] = 'Bad boys'
data.head(100)

            State      Time     Src_IP        Cat
0   NEW_PACKET_IN  02:58:15  10.0.0.80   Bad boys
1   NEW_PACKET_IN  02:58:15   10.0.0.1  Good boys
2   NEW_PACKET_IN  02:58:15   10.0.0.2  Good boys
3   NEW_PACKET_IN  02:58:15   10.0.0.3  Good boys
4   NEW_PACKET_IN  02:58:15   10.0.0.4  Good boys
5   NEW_PACKET_IN  02:58:15   10.0.0.5  Good boys
6   NEW_PACKET_IN  02:58:15   10.0.0.6  Good boys
7   NEW_PACKET_IN  02:58:15   10.0.0.4  Good boys
8   NEW_PACKET_IN  02:58:15   10.0.0.5  Good boys
9   NEW_PACKET_IN  02:58:15   10.0.0.7  Good boys
10  NEW_PACKET_IN  02:58:15   10.0.0.6  Good boys
11  NEW_PACKET_IN  02:58:15   10.0.0.3  Good boys
12  NEW_PACKET_IN  02:58:15   10.0.0.2  Good boys
13  NEW_PACKET_IN  02:58:15   10.0.0.7  Good boys
14  NEW_PACKET_IN  02:58:15   10.0.0.1  Good boys
15  NEW_PACKET_IN  02:58:15   10.0.0.8  Good boys
16  NEW_PACKET_IN  02:58:15   10.0.0.8  Good boys
17  NEW_PACKET_IN  02:58:15   10.0.0.9  Good boys
18         PASSED  02:58:15  10.0.0.80   Bad boys
19         PASSED  02:58:15   10.0.0.1  Good boys
20         PASSED  02:58:15   10.0.0.2  Good boys
21         PASSED  02:58:15   10.0.0.3  Good boys
22         PASSED  02:58:15   10.0.0.4  Good boys
23         PASSED  02:58:15   10.0.0.5  Good boys
24         PASSED  02:58:15   10.0.0.6  Good boys
25         PASSED  02:58:15   10.0.0.4  Good boys
26         PASSED  02:58:15   10.0.0.5  Good boys
27         PASSED  02:58:15   10.0.0.7  Good boys
28         PASSED  02:58:15   10.0.0.6  Good boys
29         PASSED  02:58:15   10.0.0.3  Good boys
..            ...       ...        ...        ...
70  NEW_PACKET_IN  02:58:15   10.0.0.9  Good boys
71  NEW_PACKET_IN  02:58:15  10.0.0.10  Good boys
72  NEW_PACKET_IN  02:58:15  10.0.0.10  Good boys
73  NEW_PACKET_IN  02:58:15  10.0.0.11  Good boys
74  NEW_PACKET_IN  02:58:15  10.0.0.11  Good boys
75  NEW_PACKET_IN  02:58:15  10.0.0.12  Good boys
76  NEW_PACKET_IN  02:58:15  10.0.0.12  Good boys
77  NEW_PACKET_IN  02:58:15  10.0.0.13  Good boys
78  NEW_PACKET_IN  02:58:15  10.0.0.13  Good boys
79  NEW_PACKET_IN  02:58:15  10.0.0.14  Good boys
80  NEW_PACKET_IN  02:58:15  10.0.0.14  Good boys
81  NEW_PACKET_IN  02:58:15  10.0.0.15  Good boys
82  NEW_PACKET_IN  02:58:15  10.0.0.15  Good boys
83  NEW_PACKET_IN  02:58:15  10.0.0.16  Good boys
84  NEW_PACKET_IN  02:58:15  10.0.0.16  Good boys
85  NEW_PACKET_IN  02:58:15  10.0.0.17  Good boys
86  NEW_PACKET_IN  02:58:15  10.0.0.17  Good boys
87  NEW_PACKET_IN  02:58:15  10.0.0.18  Good boys
88  NEW_PACKET_IN  02:58:15  10.0.0.18  Good boys
89  NEW_PACKET_IN  02:58:15  10.0.0.19  Good boys
90  NEW_PACKET_IN  02:58:15  10.0.0.19  Good boys
91  NEW_PACKET_IN  02:58:15  10.0.0.20  Good boys
92  NEW_PACKET_IN  02:58:15  10.0.0.20  Good boys
93  NEW_PACKET_IN  02:58:15  10.0.0.21  Good boys
94  NEW_PACKET_IN  02:58:15  10.0.0.21  Good boys
95  NEW_PACKET_IN  02:58:15  10.0.0.22  Good boys
96  NEW_PACKET_IN  02:58:15  10.0.0.22  Good boys
97  NEW_PACKET_IN  02:58:15  10.0.0.23  Good boys
98  NEW_PACKET_IN  02:58:15  10.0.0.23  Good boys
99  NEW_PACKET_IN  02:58:15  10.0.0.24  Good boys

[100 rows x 4 columns]

In [7]:
data.groupby(['Time', 'Cat', 'State']).count()

                                         Src_IP
Time     Cat       State
02:58:15 Bad boys  NEW_PACKET_IN             40
                   PASSED                    15
                   REJECTED                  25
         Good boys NEW_PACKET_IN            100
                   PASSED                    75
                   REJECTED                  25
02:58:16 Bad boys  NEW_PACKET_IN             36
                   PASSED                    10
                   REJECTED                  26
                   REJECTED_blacklisted      21
         Good boys NEW_PACKET_IN             96
                   PASSED                    50
                   REJECTED                  46
02:58:17 Good boys NEW_PACKET_IN            100
                   PASSED                    75
                   REJECTED                  25
02:58:18 Good boys NEW_PACKET_IN             92
                   PASSED                    50
                   REJECTED                  42
02:58:19 Good boys NEW_PACKET_IN            100
                   PASSED                    75
                   REJECTED                  25
02:58:20 Good boys NEW_PACKET_IN             92
                   PASSED                    50
                   REJECTED                  42
02:58:21 Good boys NEW_PACKET_IN             75
                   PASSED                    25
                   REJECTED                  50
02:58:22 Good boys NEW_PACKET_IN             50
                   REJECTED                  50
                   REJECTED_blacklisted      21
02:58:23 Good boys NEW_PACKET_IN             75
                   PASSED                    25
                   REJECTED                  50
02:58:24 Good boys NEW_PACKET_IN             50
                   REJECTED                  50
                   REJECTED_blacklisted      17
02:58:25 Good boys NEW_PACKET_IN             75
                   PASSED                    25
                   REJECTED                  50
02:58:26 Good boys NEW_PACKET_IN             50
                   REJECTED                  50
                   REJECTED_blacklisted      17
02:58:27 Good boys NEW_PACKET_IN              8
                   REJECTED                   8
                   REJECTED_blacklisted       8
02:58:29 Good boys NEW_PACKET_IN             16
                   REJECTED                  16
                   REJECTED_blacklisted      16
02:58:31 Good boys NEW_PACKET_IN             16
                   REJECTED                  16
                   REJECTED_blacklisted      16
02:58:40 Bad boys  NEW_PACKET_IN             59
                   PASSED                    15
                   REJECTED                  44
                   REJECTED_blacklisted      19

In [8]:
# sel_data = data.loc[(data['State'] == 'PASSED') | (data['State'] == 'REJECTED')]
sel_data = data.loc[(data['State'].isin(['PASSED', 'REJECTED', 'REJECTED_blacklisted', 'REJECTED_POP']))]
sel_data.head()

     State      Time     Src_IP        Cat
18  PASSED  02:58:15  10.0.0.80   Bad boys
19  PASSED  02:58:15   10.0.0.1  Good boys
20  PASSED  02:58:15   10.0.0.2  Good boys
21  PASSED  02:58:15   10.0.0.3  Good boys
22  PASSED  02:58:15   10.0.0.4  Good boys

In [9]:
sel_data.groupby(['State','Cat']).count()

                                Time  Src_IP
State                Cat
PASSED               Bad boys     40      40
                     Good boys   450     450
REJECTED             Bad boys     95      95
                     Good boys   545     545
REJECTED_blacklisted Bad boys     40      40
                     Good boys    95      95